"""Centralized market metadata for Projectr Analytics."""

MARKET_DATA = {
    "austin": {
        "name": "Austin-Round Rock, TX",
        "lat": 30.2672,
        "lon": -97.7431,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
    },
    "dallas": {
        "name": "Dallas-Fort Worth, TX",
        "lat": 32.7767,
        "lon": -96.7970,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "19100",
        "fred_jobs": "DALL148NA",
        "fred_prefix": "DALL148",
        "metro_filter": "Dallas",
    },
    "houston": {
        "name": "Houston, TX",
        "lat": 29.7604,
        "lon": -95.3698,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "26420",
        "fred_jobs": "HOUS448NA",
        "fred_prefix": "HOUS448",
        "metro_filter": "Houston",
    },
    "san-antonio": {
        "name": "San Antonio, TX",
        "lat": 29.4241,
        "lon": -98.4936,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "41700",
        "fred_jobs": "TXNA",
        "fred_prefix": "SAN448",
        "metro_filter": "San Antonio",
    },
    "new-york": {
        "name": "New York-Newark, NY-NJ",
        "lat": 40.7128,
        "lon": -74.0060,
        "state_code": "NY",
        "state_fips": "36",
        "msa_code": "35620",
        "fred_jobs": "NEWY636NA",
        "fred_prefix": "NEWY636",
        "metro_filter": "New York",
    },
    "chicago": {
        "name": "Chicago, IL-IN-WI",
        "lat": 41.8781,
        "lon": -87.6298,
        "state_code": "IL",
        "state_fips": "17",
        "msa_code": "16980",
        "fred_jobs": "CHIC917NA",
        "fred_prefix": "CHIC917",
        "metro_filter": "Chicago",
    },
    "los-angeles": {
        "name": "Los Angeles, CA",
        "lat": 34.0522,
        "lon": -118.2437,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "31080",
        "fred_jobs": "LOSA106NA",
        "fred_prefix": "LOSA106",
        "metro_filter": "Los Angeles",
    },
    "seattle": {
        "name": "Seattle-Tacoma, WA",
        "lat": 47.6062,
        "lon": -122.3321,
        "state_code": "WA",
        "state_fips": "53",
        "msa_code": "42660",
        "fred_jobs": "SEAT653NA",
        "fred_prefix": "SEAT653",
        "metro_filter": "Seattle",
    },
    "san-francisco": {
        "name": "San Francisco, CA",
        "lat": 37.7749,
        "lon": -122.4194,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41860",
        "fred_jobs": "SANF406NA",
        "fred_prefix": "SANF406",
        "metro_filter": "San Francisco",
    },
    "phoenix": {
        "name": "Phoenix, AZ",
        "lat": 33.4484,
        "lon": -112.0740,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "philadelphia": {
        "name": "Philadelphia, PA",
        "lat": 39.9526,
        "lon": -75.1652,
        "state_code": "PA",
        "state_fips": "42",
        "msa_code": "37980",
        "fred_jobs": "PHIL942NA",
        "fred_prefix": "PHIL942",
        "metro_filter": "Philadelphia",
    },
    "atlanta": {
        "name": "Atlanta, GA",
        "lat": 33.7490,
        "lon": -84.3880,
        "state_code": "GA",
        "state_fips": "13",
        "msa_code": "12060",
        "fred_jobs": "ATLA013NA",
        "fred_prefix": "ATLA013",
        "metro_filter": "Atlanta",
    },
    "miami": {
        "name": "Miami, FL",
        "lat": 25.7617,
        "lon": -80.1918,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "33100",
        "fred_jobs": "MIAM112NA",
        "fred_prefix": "MIAM112",
        "metro_filter": "Miami",
    },
    "boston": {
        "name": "Boston, MA",
        "lat": 42.3601,
        "lon": -71.0589,
        "state_code": "MA",
        "state_fips": "25",
        "msa_code": "14460",
        "fred_jobs": "BOSTN25NA",
        "fred_prefix": "BOST25",
        "metro_filter": "Boston",
    },
    "washington-dc": {
        "name": "Washington, DC",
        "lat": 38.9072,
        "lon": -77.0369,
        "state_code": "DC",
        "state_fips": "11",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "denver": {
        "name": "Denver, CO",
        "lat": 39.7392,
        "lon": -104.9903,
        "state_code": "CO",
        "state_fips": "08",
        "msa_code": "19740",
        "fred_jobs": "DENN008NA",
        "fred_prefix": "DENN008",
        "metro_filter": "Denver",
    },
    "minneapolis": {
        "name": "Minneapolis, MN",
        "lat": 44.9778,
        "lon": -93.2650,
        "state_code": "MN",
        "state_fips": "27",
        "msa_code": "33460",
        "fred_jobs": "MINN427NA",
        "fred_prefix": "MINN427",
        "metro_filter": "Minneapolis",
    },
    "detroit": {
        "name": "Detroit, MI",
        "lat": 42.3314,
        "lon": -83.0458,
        "state_code": "MI",
        "state_fips": "26",
        "msa_code": "19820",
        "fred_jobs": "DETR526NA",
        "fred_prefix": "DETR526",
        "metro_filter": "Detroit",
    },
    "las-vegas": {
        "name": "Las Vegas, NV",
        "lat": 36.1716,
        "lon": -115.1391,
        "state_code": "NV",
        "state_fips": "32",
        "msa_code": "29820",
        "fred_jobs": "LASV132NA",
        "fred_prefix": "LASV132",
        "metro_filter": "Las Vegas",
    },
    "portland": {
        "name": "Portland, OR",
        "lat": 45.5152,
        "lon": -122.6784,
        "state_code": "OR",
        "state_fips": "41",
        "msa_code": "38900",
        "fred_jobs": "PORT941NA",
        "fred_prefix": "PORT941",
        "metro_filter": "Portland",
    },
    "san-diego": {
        "name": "San Diego, CA",
        "lat": 32.7157,
        "lon": -117.1611,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41740",
        "fred_jobs": "SAND006NA",
        "fred_prefix": "SAND006",
        "metro_filter": "San Diego",
    },
    "charlotte": {
        "name": "Charlotte, NC",
        "lat": 35.2271,
        "lon": -80.8431,
        "state_code": "NC",
        "state_fips": "37",
        "msa_code": "16740",
        "fred_jobs": "CHAR737NA",
        "fred_prefix": "CHAR737",
        "metro_filter": "Charlotte",
    },
    "salt-lake-city": {
        "name": "Salt Lake City, UT",
        "lat": 40.7608,
        "lon": -111.8910,
        "state_code": "UT",
        "state_fips": "49",
        "msa_code": "41620",
        "fred_jobs": "SALT649NA",
        "fred_prefix": "SALT649",
        "metro_filter": "Salt Lake City",
    },
    "columbus": {
        "name": "Columbus, OH",
        "lat": 39.9612,
        "lon": -82.9988,
        "state_code": "OH",
        "state_fips": "39",
        "msa_code": "18140",
        "fred_jobs": "COLU139NA",
        "fred_prefix": "COLU139",
        "metro_filter": "Columbus",
    },
    "nashville": {
        "name": "Nashville, TN",
        "lat": 36.1627,
        "lon": -86.7816,
        "state_code": "TN",
        "state_fips": "47",
        "msa_code": "34980",
        "fred_jobs": "NASH547NA",
        "fred_prefix": "NASH547",
        "metro_filter": "Nashville",
    },
    "orlando": {
        "name": "Orlando, FL",
        "lat": 28.5383,
        "lon": -81.3792,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "36740",
        "fred_jobs": "ORLA712NA",
        "fred_prefix": "ORLA712",
        "metro_filter": "Orlando",
    },
    "tampa": {
        "name": "Tampa, FL",
        "lat": 27.9506,
        "lon": -82.4572,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "45300",
        "fred_jobs": "TAMP312NA",
        "fred_prefix": "TAMP312",
        "metro_filter": "Tampa",
    },
    "st-louis": {
        "name": "St. Louis, MO-IL",
        "lat": 38.6270,
        "lon": -90.1994,
        "state_code": "MO",
        "state_fips": "29",
        "msa_code": "41180",
        "fred_jobs": "STLO329NA",
        "fred_prefix": "STLO329",
        "metro_filter": "St. Louis",
    },
    "baltimore": {
        "name": "Baltimore, MD",
        "lat": 39.2904,
        "lon": -76.6122,
        "state_code": "MD",
        "state_fips": "24",
        "msa_code": "12580",
        "fred_jobs": "BALT324NA",
        "fred_prefix": "BALT324",
        "metro_filter": "Baltimore",
    },
    "pittsburgh": {
        "name": "Pittsburgh, PA",
        "lat": 40.4406,
        "lon": -79.9959,
        "state_code": "PA",
        "state_fips": "42",
        "msa_code": "38300",
        "fred_jobs": "PITT642NA",
        "fred_prefix": "PITT642",
        "metro_filter": "Pittsburgh",
    },
    "san-jose": {
        "name": "San Jose, CA",
        "lat": 37.3382,
        "lon": -121.8863,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41940",
        "fred_jobs": "SANJ006NA",
        "fred_prefix": "SANJ006",
        "metro_filter": "San Jose",
    },
    "sacramento": {
        "name": "Sacramento, CA",
        "lat": 38.5816,
        "lon": -121.4944,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "40900",
        "fred_jobs": "SACR306NA",
        "fred_prefix": "SACR306",
        "metro_filter": "Sacramento",
    },
    "indianapolis": {
        "name": "Indianapolis, IN",
        "lat": 39.7684,
        "lon": -86.1581,
        "state_code": "IN",
        "state_fips": "18",
        "msa_code": "26900",
        "fred_jobs": "INDI218NA",
        "fred_prefix": "INDI218",
        "metro_filter": "Indianapolis",
    },
    "raleigh": {
        "name": "Raleigh, NC",
        "lat": 35.7796,
        "lon": -78.6382,
        "state_code": "NC",
        "state_fips": "37",
        "msa_code": "39580",
        "fred_jobs": "RALE237NA",
        "fred_prefix": "RALE237",
        "metro_filter": "Raleigh",
    },
    "jacksonville": {
        "name": "Jacksonville, FL",
        "lat": 30.3322,
        "lon": -81.6557,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "27260",
        "fred_jobs": "JACK312NA",
        "fred_prefix": "JACK312",
        "metro_filter": "Jacksonville",
    },
    "new-orleans": {
        "name": "New Orleans, LA",
        "lat": 29.9511,
        "lon": -90.0715,
        "state_code": "LA",
        "state_fips": "22",
        "msa_code": "35380",
        "fred_jobs": "NEWO122NA",
        "fred_prefix": "NEWO122",
        "metro_filter": "New Orleans",
    },
    "memphis": {
        "name": "Memphis, TN",
        "lat": 35.1495,
        "lon": -90.0490,
        "state_code": "TN",
        "state_fips": "47",
        "msa_code": "32820",
        "fred_jobs": "MEMP447NA",
        "fred_prefix": "MEMP447",
        "metro_filter": "Memphis",
    },
    "oklahoma-city": {
        "name": "Oklahoma City, OK",
        "lat": 35.4676,
        "lon": -97.5164,
        "state_code": "OK",
        "state_fips": "40",
        "msa_code": "36420",
        "fred_jobs": "OKLA340NA",
        "fred_prefix": "OKLA340",
        "metro_filter": "Oklahoma City",
    },
    "louisville": {
        "name": "Louisville, KY",
        "lat": 38.2527,
        "lon": -85.7585,
        "state_code": "KY",
        "state_fips": "21",
        "msa_code": "31140",
        "fred_jobs": "LOUI221NA",
        "fred_prefix": "LOUI221",
        "metro_filter": "Louisville",
    },
    "milwaukee": {
        "name": "Milwaukee, WI",
        "lat": 43.0389,
        "lon": -87.9065,
        "state_code": "WI",
        "state_fips": "55",
        "msa_code": "33340",
        "fred_jobs": "MILW255NA",
        "fred_prefix": "MILW255",
        "metro_filter": "Milwaukee",
    },
    "round-rock": {
        "name": "Round Rock, TX",
        "lat": 30.5083,
        "lon": -97.6789,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
    },
    "plano": {
        "name": "Plano, TX",
        "lat": 33.0198,
        "lon": -96.6989,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "19100",
        "fred_jobs": "DALL148NA",
        "fred_prefix": "DALL148",
        "metro_filter": "Dallas",
    },
    "arlington": {
        "name": "Arlington, VA",
        "lat": 38.8799,
        "lon": -77.1068,
        "state_code": "VA",
        "state_fips": "51",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "santa-monica": {
        "name": "Santa Monica, CA",
        "lat": 34.0195,
        "lon": -118.4912,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "31080",
        "fred_jobs": "LOSA106NA",
        "fred_prefix": "LOSA106",
        "metro_filter": "Los Angeles",
    },
    "oakland": {
        "name": "Oakland, CA",
        "lat": 37.8044,
        "lon": -122.2712,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41860",
        "fred_jobs": "SANF406NA",
        "fred_prefix": "SANF406",
        "metro_filter": "San Francisco",
    },
    "fort-worth": {
        "name": "Fort Worth, TX",
        "lat": 32.7555,
        "lon": -97.3308,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "19100",
        "fred_jobs": "DALL148NA",
        "fred_prefix": "DALL148",
        "metro_filter": "Dallas",
    },
    "mesa": {
        "name": "Mesa, AZ",
        "lat": 33.4152,
        "lon": -111.8315,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "bellevue": {
        "name": "Bellevue, WA",
        "lat": 47.6101,
        "lon": -122.2015,
        "state_code": "WA",
        "state_fips": "53",
        "msa_code": "42660",
        "fred_jobs": "SEAT653NA",
        "fred_prefix": "SEAT653",
        "metro_filter": "Seattle",
    },
    "cambridge": {
        "name": "Cambridge, MA",
        "lat": 42.3736,
        "lon": -71.1097,
        "state_code": "MA",
        "state_fips": "25",
        "msa_code": "14460",
        "fred_jobs": "BOSTN25NA",
        "fred_prefix": "BOST25",
        "metro_filter": "Boston",
    },
    "jersey-city": {
        "name": "Jersey City, NJ",
        "lat": 40.7178,
        "lon": -74.0431,
        "state_code": "NJ",
        "state_fips": "34",
        "msa_code": "35620",
        "fred_jobs": "NEWY636NA",
        "fred_prefix": "NEWY636",
        "metro_filter": "New York",
    },
    "frisco": {
        "name": "Frisco, TX",
        "lat": 33.1507,
        "lon": -96.8236,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "19100",
        "fred_jobs": "DALL148NA",
        "fred_prefix": "DALL148",
        "metro_filter": "Dallas",
    },
    "georgetown": {
        "name": "Georgetown, TX",
        "lat": 30.6333,
        "lon": -97.6780,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
    },
    "sugar-land": {
        "name": "Sugar Land, TX",
        "lat": 29.5984,
        "lon": -95.6226,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "26420",
        "fred_jobs": "HOUS448NA",
        "fred_prefix": "HOUS448",
        "metro_filter": "Houston",
    },
    "irvine": {
        "name": "Irvine, CA",
        "lat": 33.6846,
        "lon": -117.8265,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "31080",
        "fred_jobs": "LOSA106NA",
        "fred_prefix": "LOSA106",
        "metro_filter": "Los Angeles",
    },
    "palo-alto": {
        "name": "Palo Alto, CA",
        "lat": 37.4419,
        "lon": -122.1430,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41940",
        "fred_jobs": "SANJ006NA",
        "fred_prefix": "SANJ006",
        "metro_filter": "San Jose",
    },
    "alexandria": {
        "name": "Alexandria, VA",
        "lat": 38.8048,
        "lon": -77.0469,
        "state_code": "VA",
        "state_fips": "51",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "silver-spring": {
        "name": "Silver Spring, MD",
        "lat": 38.9907,
        "lon": -77.0261,
        "state_code": "MD",
        "state_fips": "24",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "scottsdale": {
        "name": "Scottsdale, AZ",
        "lat": 33.4942,
        "lon": -111.9261,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "redmond": {
        "name": "Redmond, WA",
        "lat": 47.6740,
        "lon": -122.1215,
        "state_code": "WA",
        "state_fips": "53",
        "msa_code": "42660",
        "fred_jobs": "SEAT653NA",
        "fred_prefix": "SEAT653",
        "metro_filter": "Seattle",
    },
}
