"""Centralized constants and configuration for the Projectr API."""

MARKET_DATA = {
    # ── Texas ──────────────────────────────────────────
    "austin": {
        "name": "Austin, TX",
        "lat": 30.2672,
        "lon": -97.7431,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_rent": "CUUR0300SEHA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
        "approx_pop": 974000,
        "msa_pop": 2400000,
        "is_satellite": False,
        "hot_zips": ["78701", "78702", "78703", "78704", "78705", "78751", "78756", "78757"],
        "major_projects": [
            {"name": "The Republic Tower", "address": "4th & Guadalupe, ATX", "type": "Mixed-Use", "valuation": "$580,000,000", "status": "Groundbreaking", "thumbnail": "https://lh3.googleusercontent.com/aida-public/AB6AXuAFQCe_y_ZrLpwZqMUOSppJoMACa-ywyOLn-R-BM1QU3XGv6V5bQMx86TQbJsamjHi7UmUf-OiqwOWqTax4goqGZMCwFBTWrJcWSjSTtL0mHc-9zWstz4kG7jfO9eYiz5ninkF77tQAo4M7XQsKdk7QYX5L3aOfxfCtSsrtZgBLP9mahQbp5LKuFkYzFbQDg6AI1zkHKbDLrD1mopFZLy_U4kTNSW511hT2Akut5wPIikZ_tstu6HBkdIvUB5rg0_btgrOvwac3jaE"},
            {"name": "E. Riverside Lofts", "address": "Riverside Corridor", "type": "Multi-Family", "valuation": "$145,200,000", "status": "In Review", "thumbnail": "https://lh3.googleusercontent.com/aida-public/AB6AXuByjMLMSgO1-jGPIHBJKAfO_a20YeG2moWsUPL0hHwDOlniMWTNuro0h4OnO8ylhjT2d3pumzq2l1HZpucN66RfZRbtgig5qNYaBaJOIi5oGLr0NMgKQ0YhZCGueiEPaPZp74KY4jE7t62wgQCz17N-u3c8sZRUsBcafkZomjRjho7g2FjZZop0eLxzOjvuVgVqNn6eA7T7xekQxwFnI4ZpDx-YVvTiwOr8hcvEJ83EmceHC8WjbuIgD76y7GkvToyqYtk6koAYxzg"},
            {"name": "North Austin Tech Hub", "address": "Domain Northside", "type": "Commercial", "valuation": "$225,800,000", "status": "Final Inspection", "thumbnail": "https://lh3.googleusercontent.com/aida-public/AB6AXuDDW-TNUy7qJ3TE4GIhi-K8s1_yK8UGrF6khuMtiHKrBaX5xRKhbkjAyk4qKCYwtCrpC5CvLEH-tOZS4zjMcOgdX23HsLCzHwp8ZGIRr0a6nJMH5HJ9z5MFdnLQVJNaOuwwAc_Nl5MC_49qmiazHAG5Oq9nEKYqmBfhdXPIkRGPkxgzpqjNVFWv3pAHNr9u5ZMfZkuj2rm18ohNyUE0AAlgFIPezdsEIvkdzgtE1Wo7peBk21ERn3KRmfL9U5AGpcWZk3xEqzdZXy4"}
        ]
    },
    "round-rock": {
        "name": "Round Rock, TX",
        "lat": 30.5083,
        "lon": -97.6789,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
        "approx_pop": 133000,
        "msa_pop": 2400000,
        "is_satellite": True,
        "parent_market": "austin"
    },
    "pflugerville": {
        "name": "Pflugerville, TX",
        "lat": 30.4548,
        "lon": -97.6223,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
    },
    "georgetown": {
        "name": "Georgetown, TX",
        "lat": 30.6333,
        "lon": -97.6775,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
    },
    "cedar-park": {
        "name": "Cedar Park, TX",
        "lat": 30.5063,
        "lon": -97.8303,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
    },
    "san-marcos": {
        "name": "San Marcos, TX",
        "lat": 29.8833,
        "lon": -97.9414,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "12420",
        "fred_jobs": "AUST448NA",
        "fred_prefix": "AUST448",
        "metro_filter": "Austin",
    },
    "dallas": {
        "name": "Dallas-Fort Worth, TX",
        "lat": 32.7767,
        "lon": -96.7970,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "19100",
        "fred_jobs": "DALL148NA",
        "fred_rent": "CUUSA316SEHA",
        "fred_prefix": "DALL148",
        "metro_filter": "Dallas",
        "approx_pop": 1288000,
        "msa_pop": 8100000,
        "is_satellite": False,
        "hot_zips": ["75201", "75204", "75205", "75206", "75219", "75225", "75231"],
        "major_projects": [
            {"name": "Southern Gateway Deck Park", "address": "I-35E @ Marsalis", "type": "Infrastructure", "valuation": "$172,000,000", "status": "Under Construction", "thumbnail": "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=100"},
            {"name": "Field Street Tower", "address": "Field & Woodall Rogers", "type": "Commercial", "valuation": "$250,000,000", "status": "Planned", "thumbnail": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=100"}
        ]
    },
    "houston": {
        "name": "Houston, TX",
        "lat": 29.7604,
        "lon": -95.3698,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "26420",
        "fred_jobs": "HOUS448NA",
        "fred_rent": "CUUSA314SEHA",
        "fred_prefix": "HOUS448",
        "metro_filter": "Houston",
        "hot_zips": ["77002", "77004", "77005", "77006", "77007", "77008", "77019", "77024"],
    },
    "san-antonio": {
        "name": "San Antonio, TX",
        "lat": 29.4241,
        "lon": -98.4936,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "41700",
        "fred_jobs": "SANA748NA",
        "fred_prefix": "SANA748",
        "metro_filter": "San Antonio",
        "hot_zips": ["78201", "78205", "78209", "78210", "78212", "78215", "78230", "78248"],
    },
    "el-paso": {
        "name": "El Paso, TX",
        "lat": 31.7619,
        "lon": -106.4850,
        "state_code": "TX",
        "state_fips": "48",
        "msa_code": "21340",
        "fred_jobs": "ELPA348NA",
        "fred_prefix": "ELPA348",
        "metro_filter": "El Paso",
    },
    # ── West Coast ─────────────────────────────────────
    "seattle": {
        "name": "Seattle, WA",
        "lat": 47.6062,
        "lon": -122.3321,
        "state_code": "WA",
        "state_fips": "53",
        "msa_code": "42660",
        "fred_jobs": "SEAT653NA",
        "fred_prefix": "SEAT653",
        "metro_filter": "Seattle",
    },
    "bellevue": {
        "name": "Bellevue, WA",
        "lat": 47.6101,
        "lon": -122.2015,
        "state_code": "WA",
        "state_fips": "53",
        "msa_code": "42660",
        "fred_jobs": "SEAT653NA",
        "fred_prefix": "SEAT653",
        "metro_filter": "Seattle",
    },
    "redmond": {
        "name": "Redmond, WA",
        "lat": 47.6740,
        "lon": -122.1215,
        "state_code": "WA",
        "state_fips": "53",
        "msa_code": "42660",
        "fred_jobs": "SEAT653NA",
        "fred_prefix": "SEAT653",
        "metro_filter": "Seattle",
    },
    "portland": {
        "name": "Portland, OR",
        "lat": 45.5152,
        "lon": -122.6784,
        "state_code": "OR",
        "state_fips": "41",
        "msa_code": "38900",
        "fred_jobs": "PORT941NA",
        "fred_prefix": "PORT941",
        "metro_filter": "Portland",
    },
    "san-francisco": {
        "name": "San Francisco, CA",
        "lat": 37.7749,
        "lon": -122.4194,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41860",
        "fred_jobs": "SANF806NA",
        "fred_prefix": "SANF806",
        "metro_filter": "San Francisco",
        "approx_pop": 815000,
        "msa_pop": 4700000,
        "is_satellite": False,
        "major_projects": [
            {"name": "Potrero Power Station", "address": "Dogpatch Waterfront", "type": "Mixed-Use", "valuation": "$2,000,000,000", "status": "Active Phase 1", "thumbnail": "https://images.unsplash.com/photo-1449156059431-787c5b7cb39c?auto=format&fit=crop&w=100"},
            {"name": "Mission Rock", "address": "Adjacent to Oracle Park", "type": "Residential/Commercial", "valuation": "$1,000,000,000", "status": "Pre-Leasing", "thumbnail": "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=100"}
        ]
    },
    "san-jose": {
        "name": "San Jose, CA",
        "lat": 37.3382,
        "lon": -121.8863,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41940",
        "fred_jobs": "SANJ906NA",
        "fred_prefix": "SANJ906",
        "metro_filter": "San Jose",
    },
    "los-angeles": {
        "name": "Los Angeles, CA",
        "lat": 34.0522,
        "lon": -118.2437,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "31080",
        "fred_jobs": "LOSA006NA",
        "fred_prefix": "LOSA106",
        "metro_filter": "Los Angeles",
        "approx_pop": 3898000,
        "msa_pop": 12800000,
        "is_satellite": False,
        "major_projects": [
            {"name": "LACMA Building the Future", "address": "Wilshire Blvd", "type": "Cultural", "valuation": "$750,000,000", "status": "Under Construction", "thumbnail": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=100"},
            {"name": "The Grand LA", "address": "Downtown LA", "type": "Mixed-Use", "valuation": "$1,000,000,000", "status": "Active", "thumbnail": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=100"}
        ]
    },
    "san-diego": {
        "name": "San Diego, CA",
        "lat": 32.7157,
        "lon": -117.1611,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "41740",
        "fred_jobs": "SAND706NA",
        "fred_prefix": "SAND706",
        "metro_filter": "San Diego",
    },
    "sacramento": {
        "name": "Sacramento, CA",
        "lat": 38.5816,
        "lon": -121.4944,
        "state_code": "CA",
        "state_fips": "06",
        "msa_code": "40900",
        "fred_jobs": "SACR906NA",
        "fred_prefix": "SACR906",
        "metro_filter": "Sacramento",
    },
    # ── Southwest ──────────────────────────────────────
    "phoenix": {
        "name": "Phoenix, AZ",
        "lat": 33.4484,
        "lon": -112.0740,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "mesa": {
        "name": "Mesa, AZ",
        "lat": 33.4151,
        "lon": -111.8315,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "tempe": {
        "name": "Tempe, AZ",
        "lat": 33.4255,
        "lon": -111.9400,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "chandler": {
        "name": "Chandler, AZ",
        "lat": 33.3062,
        "lon": -111.8413,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "gilbert": {
        "name": "Gilbert, AZ",
        "lat": 33.3528,
        "lon": -111.7890,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "scottsdale": {
        "name": "Scottsdale, AZ",
        "lat": 33.4942,
        "lon": -111.9261,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "38060",
        "fred_jobs": "PHOE004NA",
        "fred_prefix": "PHOE004",
        "metro_filter": "Phoenix",
    },
    "tucson": {
        "name": "Tucson, AZ",
        "lat": 32.2226,
        "lon": -110.9747,
        "state_code": "AZ",
        "state_fips": "04",
        "msa_code": "46060",
        "fred_jobs": "TUCS004NA",
        "fred_prefix": "TUCS004",
        "metro_filter": "Tucson",
    },
    "las-vegas": {
        "name": "Las Vegas, NV",
        "lat": 36.1699,
        "lon": -115.1398,
        "state_code": "NV",
        "state_fips": "32",
        "msa_code": "29820",
        "fred_jobs": "LASV332NA",
        "fred_prefix": "LASV332",
        "metro_filter": "Las Vegas",
    },
    "denver": {
        "name": "Denver, CO",
        "lat": 39.7392,
        "lon": -104.9903,
        "state_code": "CO",
        "state_fips": "08",
        "msa_code": "19740",
        "fred_jobs": "DENV708NA",
        "fred_prefix": "DENV708",
        "metro_filter": "Denver",
    },
    "salt-lake-city": {
        "name": "Salt Lake City, UT",
        "lat": 40.7608,
        "lon": -111.8910,
        "state_code": "UT",
        "state_fips": "49",
        "msa_code": "41620",
        "fred_jobs": "SALT649NA",
        "fred_prefix": "SALT649",
        "metro_filter": "Salt Lake City",
    },
    "albuquerque": {
        "name": "Albuquerque, NM",
        "lat": 35.0844,
        "lon": -106.6504,
        "state_code": "NM",
        "state_fips": "35",
        "msa_code": "10740",
        "fred_jobs": "ALBU535NA",
        "fred_prefix": "ALBU535",
        "metro_filter": "Albuquerque",
    },
    # ── East Coast ─────────────────────────────────────
    "washington-dc": {
        "name": "Washington, DC",
        "lat": 38.9072,
        "lon": -77.0369,
        "state_code": "DC",
        "state_fips": "11",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "arlington": {
        "name": "Arlington, VA",
        "lat": 38.8783,
        "lon": -77.0687,
        "state_code": "VA",
        "state_fips": "51",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "alexandria": {
        "name": "Alexandria, VA",
        "lat": 38.8048,
        "lon": -77.0469,
        "state_code": "VA",
        "state_fips": "51",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "silver-spring": {
        "name": "Silver Spring, MD",
        "lat": 38.9907,
        "lon": -77.0261,
        "state_code": "MD",
        "state_fips": "24",
        "msa_code": "47900",
        "fred_jobs": "WASH911NA",
        "fred_prefix": "WASH911",
        "metro_filter": "Washington",
    },
    "new-york": {
        "name": "New York, NY",
        "lat": 40.7128,
        "lon": -74.0060,
        "state_code": "NY",
        "state_fips": "36",
        "msa_code": "35620",
        "fred_jobs": "NEWY136NA",
        "fred_prefix": "NEWY136",
        "metro_filter": "New York",
        "approx_pop": 8336000,
        "msa_pop": 19600000,
        "is_satellite": False,
        "major_projects": [
            {"name": "JFK New Terminal One", "address": "Queens, NY", "type": "Infrastructure", "valuation": "$9,500,000,000", "status": "Active Construction", "thumbnail": "https://images.unsplash.com/photo-1436491865332-7a61a109c0f3?auto=format&fit=crop&w=100"},
            {"name": "Hudson Yards Phase 2", "address": "West Side, Manhattan", "type": "Mixed-Use", "valuation": "$6,000,000,000", "status": "Permitting", "thumbnail": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=100"}
        ]
    },
    "boston": {
        "name": "Boston, MA",
        "lat": 42.3601,
        "lon": -71.0589,
        "state_code": "MA",
        "state_fips": "25",
        "msa_code": "14460",
        "fred_jobs": "BOST125NA",
        "fred_prefix": "BOST125",
        "metro_filter": "Boston",
    },
    "philadelphia": {
        "name": "Philadelphia, PA",
        "lat": 39.9526,
        "lon": -75.1652,
        "state_code": "PA",
        "state_fips": "42",
        "msa_code": "37980",
        "fred_jobs": "PHIL142NA",
        "fred_prefix": "PHIL142",
        "metro_filter": "Philadelphia",
    },
    "miami": {
        "name": "Miami, FL",
        "lat": 25.7617,
        "lon": -80.1918,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "33100",
        "fred_jobs": "MIAM112NA",
        "fred_prefix": "MIAM112",
        "metro_filter": "Miami",
    },
    "orlando": {
        "name": "Orlando, FL",
        "lat": 28.5383,
        "lon": -81.3792,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "36740",
        "fred_jobs": "ORLA112NA",
        "fred_prefix": "ORLA112",
        "metro_filter": "Orlando",
    },
    "tampa": {
        "name": "Tampa, FL",
        "lat": 27.9506,
        "lon": -82.4572,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "45300",
        "fred_jobs": "TAMP112NA",
        "fred_prefix": "TAMP112",
        "metro_filter": "Tampa",
    },
    "jacksonville": {
        "name": "Jacksonville, FL",
        "lat": 30.3322,
        "lon": -81.6557,
        "state_code": "FL",
        "state_fips": "12",
        "msa_code": "27260",
        "fred_jobs": "JACK112NA",
        "fred_prefix": "JACK112",
        "metro_filter": "Jacksonville",
    },
    "charlotte": {
        "name": "Charlotte, NC",
        "lat": 35.2271,
        "lon": -80.8431,
        "state_code": "NC",
        "state_fips": "37",
        "msa_code": "16740",
        "fred_jobs": "CHAR137NA",
        "fred_prefix": "CHAR137",
        "metro_filter": "Charlotte",
    },
    "raleigh": {
        "name": "Raleigh, NC",
        "lat": 35.7796,
        "lon": -78.6382,
        "state_code": "NC",
        "state_fips": "37",
        "msa_code": "39580",
        "fred_jobs": "RALE137NA",
        "fred_prefix": "RALE137",
        "metro_filter": "Raleigh",
    },
    "atlanta": {
        "name": "Atlanta, GA",
        "lat": 33.7490,
        "lon": -84.3880,
        "state_code": "GA",
        "state_fips": "13",
        "msa_code": "12060",
        "fred_jobs": "ATLA113NA",
        "fred_prefix": "ATLA113",
        "metro_filter": "Atlanta",
    },
    "nashville": {
        "name": "Nashville, TN",
        "lat": 36.1627,
        "lon": -86.7816,
        "state_code": "TN",
        "state_fips": "47",
        "msa_code": "34980",
        "fred_jobs": "NASH947NA",
        "fred_prefix": "NASH947",
        "metro_filter": "Nashville",
    },
    # ── Midwest ────────────────────────────────────────
    "chicago": {
        "name": "Chicago, IL",
        "lat": 41.8781,
        "lon": -87.6298,
        "state_code": "IL",
        "state_fips": "17",
        "msa_code": "16980",
        "fred_jobs": "CHIC117NA",
        "fred_prefix": "CHIC117",
        "metro_filter": "Chicago",
    },
    "minneapolis": {
        "name": "Minneapolis, MN",
        "lat": 44.9778,
        "lon": -93.2650,
        "state_code": "MN",
        "state_fips": "27",
        "msa_code": "33460",
        "fred_jobs": "MINN127NA",
        "fred_prefix": "MINN127",
        "metro_filter": "Minneapolis",
    },
    "detroit": {
        "name": "Detroit, MI",
        "lat": 42.3314,
        "lon": -83.0458,
        "state_code": "MI",
        "state_fips": "26",
        "msa_code": "19820",
        "fred_jobs": "DETR126NA",
        "fred_prefix": "DETR126",
        "metro_filter": "Detroit",
    },
    "columbus": {
        "name": "Columbus, OH",
        "lat": 39.9612,
        "lon": -82.9988,
        "state_code": "OH",
        "state_fips": "39",
        "msa_code": "18140",
        "fred_jobs": "COLU139NA",
        "fred_prefix": "COLU139",
        "metro_filter": "Columbus",
    },
    "indianapolis": {
        "name": "Indianapolis, IN",
        "lat": 39.7684,
        "lon": -86.1581,
        "state_code": "IN",
        "state_fips": "18",
        "msa_code": "26900",
        "fred_jobs": "INDI118NA",
        "fred_prefix": "INDI118",
        "metro_filter": "Indianapolis",
    },
    "kansas-city": {
        "name": "Kansas City, MO",
        "lat": 39.0997,
        "lon": -94.5786,
        "state_code": "MO",
        "state_fips": "29",
        "msa_code": "28140",
        "fred_jobs": "KANS129NA",
        "fred_prefix": "KANS129",
        "metro_filter": "Kansas City",
    },
    "st-louis": {
        "name": "St. Louis, MO",
        "lat": 38.6270,
        "lon": -90.1994,
        "state_code": "MO",
        "state_fips": "29",
        "msa_code": "41180",
        "fred_jobs": "STLO129NA",
        "fred_prefix": "STLO129",
        "metro_filter": "St. Louis",
    },
}
